### PR TITLE
Allow for update of record set name/type

### LINKED ISSUE #89: Orchestrate a delete/recreate when users attempt to update a record set name
Currently, an attempt to update a record set's `name` results in the following from the VinylDNS API, as a name change requires a delete and fresh creation:

```
Error: Request URL:
...
Request Method:
PUT
Request body:
...
Response code: 
422
Response body:
"Cannot update RecordSet's name."
```

However, `terraform-provider-vinyldns` could perform the delete and fresh create on users' behalf. Is that worth considering?

### PR DESCRIPTION
**Pull request by dgrizzanti**
## Description of the Change

Allow for record set `name` and `type` changes during an update.

Looking for feedback on this change. I don't see similar logic to this in other providers (i.e. the [dns simple](https://github.com/terraform-providers/terraform-provider-dnsimple) and [cloudflare](https://github.com/terraform-providers/terraform-provider-cloudflare/blob/master/cloudflare/resource_cloudflare_record.go)). Their update logic is more straightforward as re-names are allowed. Maybe this logic belongs directly in the VinylDNS API if the behavior is desirable?

## Why Should This Be In The Package?

Allows changes record sets more easily without an explicit manual delete/create.

## Benefits

Allows changes record sets more easily without an explicit manual delete/create.

## Possible Drawbacks

Deleting and creating records during the update may not be a desired behavior, especially since a failure could occur between the delete and create which would yield a non-desired state (no record existing).

## Verification Process

Currently lacking test updates, need to fix that

## Applicable Issues

Resolves #89

### CODE REVIEW

**Comment by dgrizzanti** [comment]
As a side note, it looks like this build is failing on `go tip` possibly due to this removal of `darwin/386` port, https://go-review.googlesource.com/c/tools/+/227552/?

**Comment by mdb** [comment]
Thanks @dgrizzanti ! Generally, I think the code and and idea seem reasonable (I would like to see some tests eventually, though, if we decide to move forward with this).

In my mind, the questions are...
* Is it weird and bad to "subversively" perform record set deletion and creation when the Terraform "lifecycle" has determined a record set update to be the proper action?
* Does Terraform elegantly handle a resource "update" scenario that results in a new resource ID? Is it really an "update" to an existing resource if we have performed a destructive action and created a new resource with a new ID?
* Is this misleading to users who may expect an in-place update with minimal impact to record resolution?

**Comment by mdb** [comment]
After speaking to @remerle , it seems that the VinylDNS team is considering reverting [PR 925](https://github.com/vinyldns/vinyldns/pull/925), which would render this PR unnecessary, as the VinylDNS API itself would handle this on clients' behalf.

@remerle will circle back with an update after sanity-checking with the VinylDNS team.

**Comment by dgrizzanti** [comment]
Going to close this since it's no longer relevant

**Pull request closed without merging**
